# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: kitpay 0.1.1 ruby lib

Gem::Specification.new do |s|
  s.name = "kitpay"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["PayPonty"]
  s.date = "2014-02-25"
  s.description = "Gem for the PayPonty API"
  s.email = "payponty.info@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.md",
    "README.md"
  ]
  s.homepage = "http://payponty.github.io/kitpay"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Gem for the PayPonty API"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<faraday>, ["~> 0.8.1"])
      s.add_runtime_dependency(%q<faraday_middleware>, ["~> 0.8.8"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<webmock>, ["~> 1.8.7"])
    else
      s.add_dependency(%q<faraday>, ["~> 0.8.1"])
      s.add_dependency(%q<faraday_middleware>, ["~> 0.8.8"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<webmock>, ["~> 1.8.7"])
    end
  else
    s.add_dependency(%q<faraday>, ["~> 0.8.1"])
    s.add_dependency(%q<faraday_middleware>, ["~> 0.8.8"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<webmock>, ["~> 1.8.7"])
  end
end

